@url = http://localhost:5012
@selected = 783071b1-4e7e-4843-9b1a-a47e40be9cfe

###
GET {{url}}/receiving-companies
Accept: application/json

###
GET {{url}}/receiving-companies/{{selected}}
Accept: application/json

###
POST {{url}}/receiving-companies
Content-Type: application/json

{
    "code": "CODE-9035",
    "name": "Farrell, Bartell and O'Reilly",
    "address": "799 Marina Street",
    "city": "East Sedrick",
    "postalCode": "88-945",
    "country": "Lebanon",
    "phone": "+48798618278",
    "email": "maximillia.spencer@bradtkeconnelly.com"
}

###
PUT {{url}}/receiving-companies/{{selected}}
Content-Type: application/json

{
    "id": "783071b1-4e7e-4843-9b1a-a47e40be9cfe",
    "code": "CODE-9935",
    "name": "Farrell, Bartell and O'Reilly",
    "address": "799 Marina Street",
    "city": "East Sedrick",
    "postalCode": "88-945",
    "country": "Lebanon",
    "phone": "+48798618278",
    "email": "maximillia.spencer@bradtkeconnelly.com"
}

###
DELETE  {{url}}/receiving-companies/{{selected}}
Accept: application/json