@url = http://localhost:5012

###
GET {{url}}/users
Authorization: Bearer {{accessToken}}
Accept: application/json


###
# @name sing_in
POST {{url}}/users/sign-in
Content-Type: application/json

{
  "email": "cr02@wp.pl",
  "password": "string"
}

###
@accessToken = {{sing_in.response.body.accessToken}}

###
GET {{url}}/users/getmetest
Authorization: Bearer {{accessToken}}


###
GET {{url}}/users/getbyid/e0e87a6d-50bd-4501-a364-772152b7ef0c
Authorization: Bearer {{accessToken}}
Accept: application/json

###
GET {{url}}/users/getbyemail/otis@renner.us
Accept: application/json

###
POST {{url}}/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "TestowyCR_03",
    "login": "testcr_03",
    "email": "cr03@wp.pl",
    "password": "P@$$w0rd",
    "role": "user"
}


###
PUT {{url}}/users/00c43119-63f6-44ed-a796-2bd7d7a1e390
Content-Type: application/json

{
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "TestowyUP",
    "login": "testup",
    "email": "tu@wp.pl",
    "password": "string",
    "role": "admin"
}

###
DELETE {{url}}/users/ab3ef5ce-136b-46da-bb4e-f115bd8555d9
Accept: application/json
