@url = http://localhost:5012
@selectedExport = 11234d72-a625-4cb2-b1c4-fb7c7c9b4f63
###
GET {{url}}/waste-export
Accept: application/json

###
GET {{url}}/waste-export/{{selectedExport}}
Accept: application/json

###
GET {{url}}/waste-export/{{selectedExport}}/wastes
Accept: application/json

###
POST {{url}}/waste-export
Content-Type: application/json

{
  "receivingCompanyOid": "32b09be0-1e44-44f6-b78f-17c9477aadd7",
  "transportCompanyOid": "1351b586-fa56-4d65-95cd-5092d7121e67",
  "bookingDate": "2024-02-26",
  "description": "Test 2024"
}


###
PUT {{url}}/waste-export/{{selectedExport}}
Content-Type: application/json

{
  "id": "{{selectedExport}}",
  "receivingCompanyOid": "32b09be0-1e44-44f6-b78f-17c9477aadd7",
  "transportCompanyOid": "1351b586-fa56-4d65-95cd-5092d7121e67",
  "bookingDate": "2024-02-26",
  "description": "Test 2029"
}

###
DELETE {{url}}/waste-export/{{selectedExport}}
Accept: application/json


###
PUT {{url}}/waste-export/{{selectedExport}}/add-wastes
Content-Type: application/json

{
  "wasteExportId": "11234d72-a625-4cb2-b1c4-fb7c7c9b4f63",
  "wastes": [
    "d3d8da49-aa30-49a5-ac36-27ddac1ff8ec",
    "09805973-af71-4619-8dd4-81dd71f663ef"
  ]
}

###
DELETE  {{url}}/waste-export/{{selectedExport}}/delete-waste/09805973-af71-4619-8dd4-81dd71f663ef
Content-Type: application/json


###
PUT {{url}}/waste-export/{{selectedExport}}/add-receivingcompany/a83322ac-fe78-447e-88e3-c5a5b80a30f3
Content-Type: application/json


###
PUT {{url}}/waste-export/{{selectedExport}}/add-transportcompany/4fde0cc9-b158-4466-bd3f-cd93bb6bdb69
Content-Type: application/json