@url = http://localhost:5012

###
GET {{url}}/wastes
Accept: application/json

###
GET {{url}}/wastes/1322b562-2a05-4ac9-8709-8dd5ac1252fb
Accept: application/json

###
POST {{url}}/wastes
Content-Type: application/json

{
  "code": "TEST-1001",
  "name": "Test 1001 description",
  "quantity": 20,
  "unit": "kg"
}


###
PUT {{url}}/wastes/ab3ef5ce-136b-46da-bb4e-f115bd8555d9
Content-Type: application/json

{
    "id": "ab3ef5ce-136b-46da-bb4e-f115bd8555d9",
  "code": "TEST-999",
  "name": "Test 999 description",
  "quantity": 20,
  "unit": "kg"
}

###
DELETE {{url}}/wastes/ab3ef5ce-136b-46da-bb4e-f115bd8555d9
Accept: application/json
